apiVersion: v1
kind: Service
metadata:
  name: chess-madra-fe
spec:
  ports:
    - port: 80
  selector:
    app: chess-madra-fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-madra-fe
spec:
  selector:
    matchLabels:
      app: chess-madra-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: chess-madra-fe
    spec:
      containers:
        - image: marcusbuffett/chess-madra-fe:latest
          name: chess-madra-fe
          ports:
            - containerPort: 80
              name: chess-madra-fe
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 2
      imagePullSecrets:
        - name: docker-hub-secret-key
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-madra-fe
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: chessmadra.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: chess-madra-fe
                port:
                  number: 80
  tls:
    - hosts:
        - chessmadra.com
      secretName: chess-madra-cert-prod
