apiVersion: v1
kind: Service
metadata:
  name: chess-madra-fe
spec:
  ports:
    - port: 5000
  selector:
    app: chess-madra-fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-madra-fe
spec:
  selector:
    matchLabels:
      app: chess-madra-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: chess-madra-fe
    spec:
      containers:
        - image: marcusbuffett/chess-madra-fe:latest
          name: chess-madra-fe
          ports:
            - containerPort: 5000
              name: chess-madra-fe
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 2
      imagePullSecrets:
        - name: docker-hub-secret-key
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-madra-fe
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
spec:
  ingressClassName: kong
  tls:
    - secretName: chess-madra-fe-tls-v3
      hosts:
        - chessmadra.mbuffett.com
  rules:
    - host: chessmadra.mbuffett.com
      http: &http_rules
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: chess-madra-fe
                port:
                  number: 5000
